### ISSUE TITLE
Dont use `.innerHTML` if `.textContent` would also work

### ISSUE THREAD

**Issue by wooorm** [Zishrodrigues/meesterproef#10]
[`script.js#L30-31`](https://github.com/Zishrodrigues/meesterproef/blob/f7817caa7200cf2d6615254b0459e0a481aa19a4/static/js/script.js#L30-L31)

**Comment by Zishrodrigues** [comment]
Upon further reading i've come to realize that .textContent is indeed faster than .innerHTML as it does not parse html, but instead uses straight text. Noted and fixed!

https://github.com/Zishrodrigues/meesterproef/commit/9f74c7f66227d69c2b4cdfbd9bb8bf06304d94d7
