### ISSUE TITLE
HTML semantics

### ISSUE THREAD

**Issue by joostf** [Zishrodrigues/meesterproef#18]
Container/wrapper elements could be more semantic 

https://github.com/Zishrodrigues/meesterproef#code-flow-work-in-progress-feedback-is-greatly-appreciated

**Comment by Zishrodrigues** [comment]
That's true. Changed meaningless <div>'s to <section> and <articles>. Thanks!

https://github.com/Zishrodrigues/meesterproef/commit/754339c1ca9ee3a7d1f46f8c8dd7e3fbd11dd4df
