### ISSUE TITLE
Keep your object names lean 'n mean

### ISSUE THREAD

**Issue by joostf** [Zishrodrigues/meesterproef#19]
consider:
```
var username = {
        check: function() {

        },
        enter: function() {

        }
};
```
username.check() is more readable then username.checkUsername()

https://github.com/Zishrodrigues/meesterproef/blob/5d4b1a893545bbbf0a7799488d7f0de5555be560/static/js/script.js#L31

var messageObj = {}; could be var message = {}; 

https://github.com/Zishrodrigues/meesterproef/blob/5d4b1a893545bbbf0a7799488d7f0de5555be560/static/js/script.js#L64

etcetera

**Comment by Zishrodrigues** [comment]
Good point. This makes my code neater and more readable. Thanks!

https://github.com/Zishrodrigues/meesterproef/commit/e07a4dddba6923f88f3bd84e13be5326e2340121
