### ISSUE TITLE
Don't use same function names

### ISSUE THREAD

**Issue by joostf** [Zishrodrigues/meesterproef#20]
```
likeComment: function() {
            ...
            function likeComment() {
                ...
            }
        }
```

https://github.com/Zishrodrigues/meesterproef/blob/5d4b1a893545bbbf0a7799488d7f0de5555be560/static/js/script.js#L101

**Comment by Zishrodrigues** [comment]
Thanks for the feedback, fixed.

https://github.com/Zishrodrigues/meesterproef/commit/e07a4dddba6923f88f3bd84e13be5326e2340121
