### ISSUE TITLE
Don’t define CSS variables on *all* elements

### ISSUE THREAD

**Issue by wooorm** [Zishrodrigues/meesterproef#6]
in [`style.css`](https://github.com/Zishrodrigues/meesterproef/blob/f7817caa7200cf2d6615254b0459e0a481aa19a4/static/css/style.css#L5-L7), you’re defining the CSS variables on all elements. Why?

Shouldn’t they be defined on the HTML element (or [`:root`](https://developer.mozilla.org/en-US/docs/Web/CSS/:root))?

**Comment by Zishrodrigues** [comment]
My thought process was probably "I'm going to use these everywhere, so i'll declare them globally".
Looking back that didn't make much sense. Fixed.

https://github.com/Zishrodrigues/meesterproef/commit/51051fbe020489efcbe587cd1ad25cc276c6d26c
