### ISSUE TITLE
CSS indentation

### ISSUE THREAD

**Issue by wooorm** [Zishrodrigues/meesterproef#7]
[`style.css#L86-94`](https://github.com/Zishrodrigues/meesterproef/blob/f7817caa7200cf2d6615254b0459e0a481aa19a4/static/css/style.css#L86-L94) contains some weird indentation!

Maybe use a [CSS linter](https://github.com/stylelint/stylelint) to catch these mistakes automatically?

**Comment by Zishrodrigues** [comment]
This is odd as the weird indentation only shows up on Github. Seems fine in the code editors.

Will have to look further into this in order to fix it

**Comment by wooorm** [comment]
Your probably using tabs and spaces together.

**Comment by Zishrodrigues** [comment]
Seems like you've pinpointed the issue precisely.

Fixed the indentation, thanks!

https://github.com/Zishrodrigues/meesterproef/commit/448e5ac90f80a0e0fa046ff6e4e1ec30a8adcecf
