### ISSUE TITLE
Use `addEventListener` instead of `on*` attributes

### ISSUE THREAD

**Issue by wooorm** [Zishrodrigues/meesterproef#8]
E.g., [`script.js#L38`](https://github.com/Zishrodrigues/meesterproef/blob/f7817caa7200cf2d6615254b0459e0a481aa19a4/static/js/script.js#L38).

**Comment by Zishrodrigues** [comment]
Upon further reading i've come to understand that 'addEventListener' is more compatible with other chunks of code one might use, as it allows for multiple events, thus making it a better choice in most situations. 

Thanks! Fixed.

https://github.com/Zishrodrigues/meesterproef/commit/b96e778c0cee22b9eff83eb2fb20c6c38a9cede4
