### ISSUE TITLE
Superfluous parentheses in `script.js`

### ISSUE THREAD

**Issue by wooorm** [Zishrodrigues/meesterproef#9]
[in `.innerHTML=(msg)`](https://github.com/Zishrodrigues/meesterproef/blob/f7817caa7200cf2d6615254b0459e0a481aa19a4/static/js/script.js#L46), the parens are not needed.

**Comment by Zishrodrigues** [comment]
Good to know. Fixed.

https://github.com/Zishrodrigues/meesterproef/commit/52e0041ac0fc059229b329d75fa0670babea5f41
